### ISSUE TITLE
Experience Button Not Scrolling to Bottom of Section

### ISSUE THREAD

**Issue by the-shivam-gupta** [nirmal141/html_portfolio#1]
Issue:
The "Experience" button in the header is not functioning as expected. Upon clicking the button, it should scroll the user to the bottom of the experience section, but it fails to do so.

Expected Behavior:
When the "Experience" button is clicked, the page should smoothly scroll to the bottom of the experience section, allowing users to view all the content.

**Comment by nirmal141** [comment]
Changes Done. Thanks a Lot, appreciate your feedback!

**Comment by nirmal141** [comment]
> Issue: The "Experience" button in the header is not functioning as expected. Upon clicking the button, it should scroll the user to the bottom of the experience section, but it fails to do so.
> 
> Expected Behavior: When the "Experience" button is clicked, the page should smoothly scroll to the bottom of the experience section, allowing users to view all the content.

Changes Done, Thanks a lot, appreciate your feedback!
